# Generated by Django 5.1.6 on 2025-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='img',
            field=models.URLField(default='', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.URLField(default='', verbose_name='Photo'),
        ),
    ]
