# Generated by Django 5.1.6 on 2025-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_services_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
        ),
    ]
