# Generated by Django 5.1.6 on 2025-02-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Photo'),
        ),
    ]
