# Generated by Django 5.1.6 on 2025-02-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mini_desc',
            field=models.TextField(default='', verbose_name='Mini Description'),
        ),
    ]
