# Generated by Django 5.1.6 on 2025-02-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
