# Generated by Django 5.1.6 on 2025-02-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_remove_reviews_name_reviews_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='img',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
    ]
